### ISSUE TITLE
Is it possible to change the name of sync-blacklist.txt?

### ISSUE THREAD

**Issue by s-makin** [canonical/ubuntu-maintainers-handbook#111]
In the course of my polishing I've found several instances of the word blacklist, which should be avoided according to our inclusive language guidelines. I've been changing instances I found (where I sensibly could) to "blocklist" instead, but in Proposed Migration there's a reference to a file called "sync-blacklist.txt". Is it within our control to change the name of that file, and what would be the implications? (or, has this already been raised and the file name already changed?)

**Comment by cpaelzer** [comment]
It wasn't ready back then, but yeah since then
https://ubuntu-archive-team.ubuntu.com/sync-blacklist.txt changed to also be https://ubuntu-archive-team.ubuntu.com/sync-blocklist.txt

Same as the tool managing it in ubuntu-archive-tools in
https://git.launchpad.net/ubuntu-archive-tools/commit/?id=92334dc3eb7d558d9b16255aba18c9d38aa2b6b6
